# Generated by Django 5.2.8 on 2025-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Date_of_manufacturing', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('rate', models.IntegerField()),
                ('quantity', models.IntegerField(max_length=10)),
                ('about_the_product', models.CharField(max_length=100)),
            ],
        ),
    ]
